### ISSUE TITLE
 Error: Error updating DvmCmdAddDevice resource: │ err -20042: Probe failed: network

### ISSUE THREAD

**Issue by maajin** [fortinetdev/terraform-provider-fortimanager#10]
I am trying to add fortigate to fortimanager using terraform but getting below error.

Both fortimanger & fortigate are in AWS & on same network.

 Error: Error updating DvmCmdAddDevice resource:
│ err -20042: Probe failed: network
│
│   with fortimanager_dvm_cmd_add_device.trname,
│   on fortimanager_test.tf line 21, in resource "fortimanager_dvm_cmd_add_device" "trname":
│   21: resource "fortimanager_dvm_cmd_add_device" "trname" {
│

**Comment by lix-fortinet** [comment]
Hi @maajin,

Thank you for raising this issue. I would appreciate it if you could provide your configuration and test environment, like FortiManager version, Terraform FortiManager provider version, FortiGate version. So that we could reproduce the issue on our side. 

Thanks,
Xing

**Comment by MaxxLiu22** [comment]
I will go ahead to close this case, if you still have questions, feel free to reopen it or another case.
