### ISSUE TITLE
Error creating fortimanager_object_webfilter_profile

### ISSUE THREAD

**Issue by pedrojgsbraga** [fortinetdev/terraform-provider-fortimanager#11]
Hi,

I'm trying to create the webfilter_profile and I get an error when call the webfilter_urlfilter (urlfilter_table).

`resource "fortimanager_object_webfilter_urlfilter" "webfilter_urlfilter" {
  scopetype = "adom"
  adom      = "XX"
  name      = "XX-webfilter_urlfilter"
  fosid = 1
  entries {
    url    = "XX.org"
    type   = "wildcard"
    action = "allow"
    status = "enable"
  }
}

resource "fortimanager_object_webfilter_profile" "webfilter_profile" {
  scopetype   = "adom"
  adom        = "XX"
  name        = "XX-egress"
  feature_set = "flow"
  extended_log = "disable"

   web {
    urlfilter_table     = "1"
  }
} `

The error message is:
Error: Error creating ObjectWebfilterProfile resource:
err -10: The data is invalid for selected url

versions:
Terraform v0.13.7
fortinetdev/fortimanager = 1.3.6
fortimanager = 7.0.2

Thank you.

**Comment by lix-fortinet** [comment]
Hi @pedrojgsbraga,

This issue has been fixed in the latest release of FortiManager Terraform provider v1.5.0. Please switch to the latest version of FortiManager Terraform provider and try it again.

Please let me know if you have any questions.

Thanks,
Xing

**Comment by MaxxLiu22** [comment]
I will go ahead to close this case, if you still have questions, feel free to reopen it or another case.
