### ISSUE TITLE
unable to use fortimanager provider on M1 mac

### ISSUE THREAD

**Issue by wcameronbowen** [fortinetdev/terraform-provider-fortimanager#12]
Receive the following error when attempting to use the fortimanager provider on macOS 12.2.1 with an M1 (arm-based) mac. There is clearly a binary compiled for [darwin_amd64](https://github.com/fortinetdev/terraform-provider-fortimanager/releases/tag/1.3.6) in version 1.3.6. Any chance I'm missing something?

> Error: Incompatible provider version
>
> Provider registry.terraform.io/fortinetdev/fortimanager v1.3.6 does not have a package available for your current platform, darwin_arm64.
>
>Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.

**Comment by lix-fortinet** [comment]
Hi @wcameronbowen,

Thank you for raising this issue. We will support darwin_arm64 in the next release. And we will get back to you when the new version of FortiManager Terraform provider released.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @wcameronbowen,

The latest release of FortiManager Terraform provider v1.4.0 supports darwin_arm64.

Thanks,
Xing
