### ISSUE TITLE
Forced re-creation of imported resources

### ISSUE THREAD

**Issue by KB30497** [fortinetdev/terraform-provider-fortimanager#13]
Hello,

I'm trying to import existing Fortimanager configuration into Terraform state, however the 'scopetype' attribute on the imported resources gets set to null, which means Terraform will force re-creation of the resources on the next apply.

For example with importing an address group:

The import itself works fine:
```
terraform import module.objects.fortimanager_object_firewall_addrgrp.address_group["test-group02"] "test-group02"

module.objects.fortimanager_object_firewall_addrgrp.address_group["test-group02"]: Importing from ID "test-group02"...

module.objects.fortimanager_object_firewall_addrgrp.address_group["test-group02"]: Import prepared!
  Prepared fortimanager_object_firewall_addrgrp for import
module.objects.fortimanager_object_firewall_addrgrp.address_group["test-group02"]: Refreshing state... [id=test-group02]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

But if we look at the imported state for the resource we can see that 'scopetype' is imported as null:

```json
{
  "module": "module.objects",
  "mode": "managed",
  "type": "fortimanager_object_firewall_addrgrp",
  "name": "address_group",
  "provider": "provider[\"registry.terraform.io/fortinetdev/fortimanager\"]",
  "instances": [
	{
	  "index_key": "test-group02",
	  "schema_version": 0,
	  "attributes": {
		...
		"name": "test-group02",
		"scopetype": null,
		"tagging": [],
		"type": "default",
		"uuid": "f376021a-9b0e-51ec-64a3-9398bf9a389b",
		"visibility": ""
	  },
	}
    ]
}
```

Which results in the next apply forcing the recreation of the resource as it defaults to 'inherit':
```hcl
  # module.objects.fortimanager_object_firewall_addrgrp.address_group["test-group02"] must be replaced
-/+ resource "fortimanager_object_firewall_addrgrp" "address_group" {
        name                  = "test-group02"
      + scopetype             = "inherit" # forces replacement
      ~ uuid                  = "f376021a-9b0e-51ec-64a3-9398bf9a389b" -> (known after apply)
```

Is there some piece that I'm missing? This seems to kind of defeat the purpose of importing existing configuration.

**Comment by lix-fortinet** [comment]
Hi @KB30497,

Thank you for raising this issue. Team are working on this issue. We will get back to you ASAP.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @KB30497,

This issue has been fixed in the latest release of FortiManager Terraform provider v1.4.0. Please use the latest version of FortiManager Terraform provider and try it again.

Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @KB30497,

I'm going to close this issue since it was resolved and has been inactive for a few months. You are very welcome to open a new issue if you have any other questions.
	
Thanks,
Xing
