### ISSUE TITLE
resource_object_cli_template missing template type

### ISSUE THREAD

**Issue by poroping** [fortinetdev/terraform-provider-fortimanager#14]
Type can be `cli` or `jinja`

ref: https://fndn.fortinet.net/index.php?/fortiapi/5-fortimanager/1495/5/pm/config/cli/

**Comment by lix-fortinet** [comment]
Hi @poroping,

Thank you for raising this issue. Team are working on this issue. And we will fix it in the next release. We will get back to you once it's resolved. Before that, you could use the generic resource as alternatives:
https://registry.terraform.io/providers/fortinetdev/fortimanager/latest/docs/resources/fortimanager_json_generic_api

Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @poroping,

This issue has been fixed in the latest release of FortiManager Terraform provider v1.4.0. Please use the latest version of FortiManager Terraform provider and try it again.

Please let me know if you have any questions.

Thanks,
Xing

**Comment by poroping** [comment]
Resolved thank you.
