### ISSUE TITLE
ETA for darwin_arm64 support?

### ISSUE THREAD

**Issue by tiagoasousa** [fortinetdev/terraform-provider-fortimanager#16]
Hi any ETA for darwin_arm64 support?

**Comment by lix-fortinet** [comment]
Hi @tiagoasousa,

Thank you for raising this issue. We will have a new release in two weeks.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @tiagoasousa,

The latest release of FortiManager Terraform provider v1.4.0 supports darwin_arm64. 

Thanks,
Xing
