### ISSUE TITLE
fortimanager_securityconsole

### ISSUE THREAD

**Issue by ozid** [fortinetdev/terraform-provider-fortimanager#18]
Hello,

I figure out how manipulate objects and policy but i have a trouble to understand how install/commit the policy package to the fortigate..

I'm not sure to understand the equivalent of doing:
- Lock ADOM
- Policy & Objects -> Install -> **Install Wizard**
- Unlock ADOM

I try this:

```
resource "fortimanager_securityconsole_install_package" "default" {
  fmgadom           = <adom_name>
  adom_rev_comments = "blabla"
  adom_rev_name     = "blabla"
  dev_rev_comments  = "blabla"
  flags             = ["auto_lock_ws", "check_pkg_st", "copy_assigned_pkg", "cp_all_objs", "generate_rev", "preview"]
  pkg               = <policy_package_name>
  force_recreate    = uuid()
  scope {
    name = "<firewall_name>"
    vdom = "<vdom_name>"
  }
  depends_on = [fortimanager_exec_workspace_action.unlockres]
}

resource "fortimanager_securityconsole_package_commit" "defaultcommit" {
  fmgadom        = <adom_name>
  force_recreate = uuid()
  scope {
    name = "<firewall_name>"
    vdom = "<vdom_name>"
  }
  depends_on = [fortimanager_securityconsole_install_package.default]
}
```

But this is not installing the policy package on the device, in formatimanager task monitor:

![image](https://user-images.githubusercontent.com/40234451/162459728-8582703f-2738-477c-9dd4-1c3664583678.png)
![image](https://user-images.githubusercontent.com/40234451/162460531-93d75bd4-f5a1-4998-a6b7-2b55940b598e.png)
loading for ever without success. i had to delete the task

in event logs i see:
**No Installation Targets on package<policy_package_name>**

I'm also not sure if i should include "preview" flags with other flags or if it should be left alone.

There is something i don't understand with package install can someone help me or provide me an example of a working configuration to apply policy to a device/vdom (all settings include objects/policy and so on..)

Thanks you,

**Comment by ozid** [comment]
I notice the error:  No Installation Targets on package<policy_package_name>
Is here because there was no new policy to add.

I added a policy and run terraform again and i notice the task is stuck:
![image](https://user-images.githubusercontent.com/40234451/162697543-af249df8-c058-439b-ac5b-86c11303829d.png)

But event log seem to show a success commit:
![image](https://user-images.githubusercontent.com/40234451/162697831-daba00e1-4609-4aa5-998f-63a627321138.png)

**Comment by lix-fortinet** [comment]
Hi @ozid,

Thank you for raising this issue. Team are working on this issue. We will get back to you when we have some updates.

Thanks,
Xing

**Comment by ozid** [comment]
Hello thanks, i try also:

```
resource "fortimanager_securityconsole_install_package" "default" {
  fmgadom               = var.adom
  dev_rev_comments      = "applied by terraform"
  flags                 = ["auto_lock_ws", "cp_all_objs", "copy_assigned_pkg", "check_pkg_st",  "preview"]
  pkg                   = var.policy-package
  force_recreate        = uuid()
  dynamic_sort_subtable = "false"
  scope {
    name                = var.scope-fw-name
    vdom                = var.scope-vdom
  }
  depends_on            = [fortimanager_exec_workspace_action.unlockres]
}

resource "fortimanager_securityconsole_package_commit" "defaultcommit" {
  fmgadom               = var.adom
  force_recreate        = uuid()
  dynamic_sort_subtable = "false"
  scope {
    name                = var.scope-fw-name
    vdom                = var.scope-vdom
  }
  depends_on            = [fortimanager_securityconsole_install_package.default]
}
```

result cli fortimanager:
```
FMG-VM64-AWS # __send_gui_notify: {"msg":"notify", "from":"backend","collection":"workspace","method":"lock","params":{"adom_oid":1714,"dev_oid":1714,"obj_oid":0}}
__send_gui_notify: {"msg":"notify", "from":"backend","collection":"workspace","method":"unlock","params":{"adom_oid":1714,"dev_oid":1714,"obj_oid":0}}
__send_gui_notify: {"msg":"notify", "from":"backend","collection":"workspace","method":"lock","params":{"adom_oid":1714,"dev_oid":1714,"obj_oid":0}}
__send_gui_notify: {"msg":"notify", "from":"backend","collection":"workspace","method":"unlock","params":{"adom_oid":1714,"dev_oid":1714,"obj_oid":0}}
Request:
{ "client": "\/usr\/local\/apache2\/bin\/httpd:23933", "method": "exec", "params": [{ "data": { "adom": "TEST", "dev_rev_comments": "applied by terraform", "flags": ["check_pkg_st", "preview", "auto_lock_ws", "copy_assigned_pkg", "cp_all_objs"], "pk
g": "TEST-POLICYPACKAGE", "scope": [{ "name": "TEST", "vdom": "WAN"}]}, "target start": 1, "url": "\/securityconsole\/install\/package"}], "session": "ZzFp0aGjhUkaDt4SAmAxaIsqdgqsdgqdsglTOUeZpX2OxOtrW72eHUxb4BP7azA
S", "src": "myip", "verbose": 1}
Chkperm Response:
{ "result": [{ "status": { "code": 0, "message": "OK"}, "url": "\/securityconsole\/install\/package"}], "session": 31027}
Response:
{ "result": [{ "data": { "task": 4590}, "status": { "code": 0, "message": "OK"}, "url": "\/securityconsole\/install\/package"}]}
__send_gui_notify: {"msg":"notify", "from":"backend","collection":"workspace","method":"lock","params":{"adom_oid":1714,"dev_oid":1714,"obj_oid":0}}
SECURITY_CONSOLE: securityconsole.c:827, mm start adom_id=1714, pkg=4251, flags=3013 "cp_all_objs preview cp_assigned_pkg "
Request:
{ "client": "\/usr\/local\/apache2\/bin\/httpd:23933", "method": "exec", "params": [{ "data": { "adom": "TEST", "scope": [{ "name": "TEST", "vdom": "WAN"}]}, "target start": 1, "url": "\/securityconsole\/package\/commit"}], "session": "ZzFp0aGjhU
kaDt4SAmAxaILPqsdgqsdgsqdgOxOtrW72eHUxb4BP7azAS", "src": "myip", "verbose": 1}
Chkperm Response:
{ "result": [{ "status": { "code": 0, "message": "OK"}, "url": "\/securityconsole\/package\/commit"}], "session": 31027}
Response:
{ "result": [{ "data": { "task": 4591}, "status": { "code": 0, "message": "OK"}, "url": "\/securityconsole\/package\/commit"}]}
SECURITY_CONSOLE: security_console_reclaim_child,597: try to reclaim child...
SECURITY_CONSOLE: reap child 23968 (0)
SECURITY_CONSOLE: refresh wait queue, triggered session=31027
SECURITY_CONSOLE: Load shared objects time: 0 hours 0 minutes 0.176445 seconds.
SECURITY_CONSOLE: Load device candidates n=1 SECURITY_CONSOLE: : 0 hours 0 minutes 0.001040 seconds.
SECURITY_CONSOLE: dev=1665,vdom=101 up to date
SECURITY_CONSOLE: device 1665 was unlocked/up_to_date
Global Handle handle refcnt = 2
SECURITY_CONSOLE: securityconsole.c:862(), mm finish adom_id=1714
__send_gui_notify: {"msg":"notify", "from":"backend","collection":"workspace","method":"unlock","params":{"adom_oid":1714,"dev_oid":1714,"obj_oid":0}}
SECURITY_CONSOLE: security_console_reclaim_child,597: try to reclaim child...
SECURITY_CONSOLE: reap child 23965 (0)
SECURITY_CONSOLE: refresh wait queue, triggered session=31027

```

But the result is the same, the commit stuck at 5% ..

**Comment by lix-fortinet** [comment]
Hi @ozid,

I hope you are doing well! Here we have some updates about this issue.

The reason of the task stuck on 5% is that the commit operation could not find a preview cache to commit. So, it just stuck there. Based on our investigation, here are some scenarios that could cause this error:
    1. No waiting for preview been installed. It may take seconds to create the preview successfully. Before that, if we trigger the commit operation, it will not find the preview cache. In the customer scenario, `fortimanager_securityconsole_package_commit` will be triggered once the install_package task created, and will not wait for the task completed.
    2. Too many flags in resource `fortimanager_securityconsole_install_package`. If we just set `preview` in argument of `flags`, preview cache will be created and commit operation could find it. However, once we set other flags except "cp_all_objs", like flags = ["check_pkg_st", "preview"], the commit operation also could not find the preview cache. We will work with API team to make some improvement for this issue. And also, we will update the example in our document.
    3. No changes for the target package. If there are no changes for the target packages, there will be no preview caches. So that commit operation will have the same error.

Here are some solutions:
    1. Set argument `flags` to only contains 'none', and do not need to use resource `fortimanager_securityconsole_package_commit`. It will auto-install the package to device if set `flags` to 'none'. Here is an example:
```
resource "fortimanager_securityconsole_install_package" "default" {
  fmgadom           = "root"
  flags             = ["none"] 
  pkg               = <YOUR PACKAGE NAME>
  force_recreate    = uuid()
}
```

    2. Set argument `flags` to only contains 'preview', and add the resource of `time_sleep` between `fortimanager_securityconsole_install_package` and `fortimanager_securityconsole_package_commit`. In this way, we could wait for the preview cache completed. Here is an example:
```
resource "fortimanager_securityconsole_install_package" "default" {
  fmgadom           = "root"
  flags             = ["preview"]
  pkg               = <YOUR PACKAGE NAME>
  force_recreate    = uuid()
}

resource "time_sleep" "wait_20_seconds" {
  depends_on = [fortimanager_securityconsole_install_package.default]

  create_duration = "20s"
  triggers = {
    force_recreate = uuid()
  }
}

resource "fortimanager_securityconsole_package_commit" "defaultcommit" {
  fmgadom        = "root"
  force_recreate = uuid()
  depends_on = [time_sleep.wait_20_seconds] }
}
```

We will continually work with related teams on this issue to improve using experience. Please let me know if you have any questions.

Thanks,
Xing

**Comment by ozid** [comment]
Thanks you !
