### ISSUE TITLE
fortimanager_object_firewall_address destroying

### ISSUE THREAD

**Issue by ozid** [fortinetdev/terraform-provider-fortimanager#19]
Hello,

I really don't undestand this issue:

1 - I add a resource to terraform:
```
resource "fortimanager_object_firewall_address" "test" {
  name         = "test"
  policy_group = "test"
  scopetype    = "inherit"
  obj_type     = "ip"
  type         = "ipmask"
  subnet       = [
    "1.1.1.1",
    "255.255.255.255",
  ]
  depends_on = [fortimanager_exec_workspace_action.lockres]
}
```

2 - I import the existing resource from the global database to this new resource:
`terraform import fortimanager_object_firewall_address.test test`

3- I run terraform apply
```
`fortimanager_exec_workspace_action.unlockres: Destroying... [id=workspaceactionglobalunlock]
fortimanager_exec_workspace_action.unlockres: Destruction complete after 0s
fortimanager_object_firewall_address.test: Destroying... [id=test]
╷
│ Error: Error deleting ObjectFirewallAddress resource: 
│ err -10015: used`

```

It seem evident if the provider delete ressource before re-creating them it will cause an issue on used objects inside policy.. I don't understand the logic here, can you explain me? In the GUI i'm able to remove an object even used inside a policy..

Thanks

**Comment by ozid** [comment]
i notice a dependency to another ADOM for this. so it can be closed, sorry

**Comment by ozid** [comment]
I notice this is when the object is assigned to an ADOM
![image](https://user-images.githubusercontent.com/40234451/162948675-2015f747-932e-4914-9f84-fffe6cbc69dc.png)

This is indeed not possible to remove in GUI also but... then how i'am supposed to use the terraform if it's stuck while trying to delete the ressource? 

The idea is to use a centralized address book managable by terraform for all adom

**Comment by lix-fortinet** [comment]
Hi @ozid,

Thank you for raising this issue. Team are working on this issue. We will get back to you when we have any updates.

Thanks,
Xing

**Comment by MaxxLiu22** [comment]
I will go ahead to close this case, if you still have questions, feel free to reopen it or another case.
