### ISSUE TITLE
fortimanager_object_cli_templategroup member definiton

### ISSUE THREAD

**Issue by tiagoasousa** [fortinetdev/terraform-provider-fortimanager#2]
Hi the resource fortimanager_object_cli_templategroup is enforcing that member be a string, but on the API and on FMG its is possible to set multiple members per template group

if put via API event the tf plan fails with:
Error: Error reading ObjectCliTemplateGroup resource from API: Error reading member: member: '' expected type 'string', got unconvertible type '[]interface {}'

**Comment by lix-fortinet** [comment]
Hi @tiagoasousa ,

Thank you for raising this issue. Team is working on this issue. And we will fix it in the next release. Before that, you could use the generic resource as alternatives:
`https://registry.terraform.io/providers/fortinetdev/fortimanager/latest/docs/resources/fortimanager_json_generic_api`
For example:
```
resource "fortimanager_json_generic_api" "test1" {
  json_content = <<JSON
{
    "method": "add",
    "params": [
        {
            "url": "/pm/config/global/obj/cli/template-group",
            "data": {
              "member": ["<member1>", "<member2>"],
              "name": "<name>"
            }
        }
    ]
}
JSON
}
```
Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @tiagoasousa ,

V1.3.5 fixed this issue and has been released. Please upgrade to the latest version of FortiManager Terraform provider and try it again.

Please let me know if you have any questions.

Thanks,
Xing
