### ISSUE TITLE
fortimanager_object_firewall_addrgrp global-object

### ISSUE THREAD

**Issue by ozid** [fortinetdev/terraform-provider-fortimanager#20]
Hello,

Can you define what is:

**[global_object]- Global-Object.**
https://registry.terraform.io/providers/fortinetdev/fortimanager/latest/docs/resources/fortimanager_object_firewall_addrgrp

Does scopetype = "global" override this option? Or should it be set ? 

Thanks

**Comment by lix-fortinet** [comment]
Hi @ozid,

Thank you for raising this issue. `global-object` is an attribute of API /pm/config/firewall/addrgrp for FortiManager database v6.4 and before. It is different with scopetype = "global". If you want to apply to global database, you need to set scopetype to "global".

Thanks,
Xing

**Comment by ozid** [comment]
Ok 

Thanks you !
