### ISSUE TITLE
Global assignment 

### ISSUE THREAD

**Issue by ozid** [fortinetdev/terraform-provider-fortimanager#21]
Hello,

I'm trying to do the equivalent of:

Global database -> Policy packages -> Assignment -> Assign selected -> Assign ALL objects.

But i didn't find a ressource for doing this. 

The idea is to push all global objects / policy on all ADOM by using terraform.

Thanks

**Comment by lix-fortinet** [comment]
Hi @ozid,

Thank you for raising this issue. Currently, we do not have a resource to do this. You could use generic resource to directly send HTTP request(https://registry.terraform.io/providers/fortinetdev/fortimanager/latest/docs/resources/fortimanager_json_generic_api). However, the API I found to assign package is `/securityconsole/assign/package`(https://fndn.fortinet.net/index.php?/fortiapi/5-fortimanager/1515/5/securityconsole/assign/), and it only could do the operations like assign/unassign for existing assignment. I will talk with related team to figure out how to implement it through REST API. And we will get back to you if we have a solution. 

Thanks,
Xing

**Comment by ozid** [comment]
Hello, ok thanks you. Do you have any updates on this? it make the usage of global objects very difficult to automate with any kind of solution

**Comment by lix-fortinet** [comment]
Hi @ozid,

We added a new resource `fortimanager_securityconsole_assign_package` in the latest FortiManager Terraform provider release(v1.5.0). This resource could assign/unassign for existing assignments. But we're still working on how to create a new assignment. Please switch to the latest version of FortiManager Terraform provider and check whether this could resolve your issue.

Thanks,
Xing

**Comment by MaxxLiu22** [comment]
I will go ahead to close this case, if you still have questions, feel free to reopen it or another case.
