### ISSUE TITLE
fortimanager_object_firewall_service_custom - session_ttl attribute -  terraform expects wrong datatype?

### ISSUE THREAD

**Issue by sognern** [fortinetdev/terraform-provider-fortimanager#23]
tf provider version: 1.4.0
fortiManager version: 7.0.2

I'm trying to create a custom service:

resource "fortimanager_object_firewall_service_custom" "test {
  app_service_type = "disable"
  color            = 1
  comment          = "comment"
  helper           = "auto"
  name             = "test"
  protocol         = "TCP/UDP/SCTP"
  proxy            = "disable"
}

Object gets created in fortimanager, but it seems like api is returning float64, but tf expects string?

Error: Error reading ObjectFirewallServiceCustom resource from API: Error reading session_ttl: session_ttl: '' expected type 'string', got unconvertible type 'float64'
with fortimanager_object_firewall_service_custom.test
on services.tf line 33, in resource "fortimanager_object_firewall_service_custom" "test":

**Comment by lix-fortinet** [comment]
Hi @sognern,

Thank you for raising this issue. We will fix it in the next release. Before that, you could use the generic resource as alternatives:
https://registry.terraform.io/providers/fortinetdev/fortimanager/latest/docs/resources/fortimanager_json_generic_api
For instance:
```
resource "fortimanager_json_generic_api" "test" {
  json_content = <<JSON
{
    "method": "add",
    "params": [
        {
            "url": "/pm/config/adom/root/obj/firewall/service/custom",
            "data": {
                "app-service-type": "disable",
                "color": 1,
                "comment": "comment",
                "helper": "auto",
                "name": "test",
                "protocol": "TCP/UDP/SCTP",
                "proxy": "disable"
            }
        }
    ]
}
JSON
}
```
Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @sognern,

This issue has been fixed in the latest release of FortiManager Terraform provider v1.5.0. Please switch to the latest version of FortiManager Terraform provider and try it again.

Please let me know if you have any questions.

Thanks,
Xing

**Comment by sognern** [comment]
Hi,
 I can confirm that the original issue  for this thread seems to be fixed in 1.5.0! Thanks!
Can you shed some light on how to create a service with multiple ports/portranges?
I've tried several ways, setting tcp_portrange below, trying to add two tcp ports: 8086 and 2003 as destination;

resource "fortimanager_object_firewall_service_custom" "test-tcp" {
  name             = "test-tcp"
  protocol         = "TCP/UDP/SCTP"
  
  tcp_portrange    = "8086-8086:0‑65535 2003-2003:0-65535"
  tcp_portrange    = "8086:0‑65535 2003:0-65535"
  tcp_portrange    = "8086-8086, 2003-2003"
  tcp_portrange    = "8086 2003"
  tcp_portrange    = "8086, 2003"

  app_service_type = "disable"
  color            = 1
  comment          = "comment"

TIA

**Comment by lix-fortinet** [comment]
Hi @sognern,

Thank you for your update. Both `"2003 8086"`, `"2003, 8086"` and `"2003-2003, 8086-8086"` for parameter `tcp_portrange` works in my side. You could see it in the firewall service list:
![image](https://user-images.githubusercontent.com/71158051/186284719-61985f0e-7faf-47b9-86b5-029a6422a88b.png)

However, you will not see the full `tcp_portrange` if you go into this resource:
![image](https://user-images.githubusercontent.com/71158051/186284969-94079570-4197-429b-b4ee-e2fd2bda1a70.png)

This maybe a GUI issue, we will open an internal ticket to track this issue. And we will get back to you once we have any update.

Thanks,
Xing

**Comment by MaxxLiu22** [comment]
This issue should have be fixed, since the data type of ``tcp_portrange`` in Terraform has changed from string to list. I will go ahead and close this case. If you still have this issue, feel free to open a new case.
