### ISSUE TITLE
fortimanager_object_firewall_address name can't contain slash

### ISSUE THREAD

**Issue by maxaudron** [fortinetdev/terraform-provider-fortimanager#24]
tf provider version: 1.4.0
FortiManager version: 6.4.8

Creating a firewall address object with a / in the name fails to create with the error after confirming the apply:

```
╷
│ Error: Error reading ObjectFirewallAddress resource:
│ err -3: Object does not exist
│
│   with fortimanager_object_firewall_address.vapor-systems,
│   on main.tf line 33, in resource "fortimanager_object_firewall_address" "vapor-systems":
│   33: resource "fortimanager_object_firewall_address" "vapor-systems" {
│
╵
```

Any subsequent plans fail with the same error. This seems to be a problem with how the URL is built, not escaping the slash properly:
```
fortimanager_object_firewall_address.vapor-systems: Refreshing state... [id=195.201.245.25/32_vapor.systems]
2022-07-08T13:16:29.054+0200 [DEBUG] provider.terraform-provider-fortimanager_v1.4.0: 2022/07/08 13:16:29 shengh: /pm/config/adom/K8s-STAGE/obj/firewall/address/195.201.245.25/32_vapor.systems
2022-07-08T13:16:29.405+0200 [DEBUG] provider.terraform-provider-fortimanager_v1.4.0: 2022/07/08 13:16:29 FMG reading response: { "result": [ { "status": { "code": -3, "message": "Object does not exist" }, "url": "\/pm\/config\/adom\/K8s-STAGE\/obj\/firewall\/address\/195.201.245.25\/32_vapor.systems" } ] }
```

The resource I'm applying:

```hcl
resource "fortimanager_object_firewall_address" "vapor-systems" {
  name = "195.201.245.25/32_vapor.systems"

  type     = "ipmask"

  subnet = [
    "195.201.245.25",
    "255.255.255.255",
  ]
}
```

This naming scheme is convention for us, and we have plenty of addresses created through the UI that work fine.

**Comment by lix-fortinet** [comment]
Hi @maxaudron,

This issue has been fixed in the latest release of FortiManager Terraform provider v1.5.0. Please switch to the latest version of FortiManager Terraform provider and try it again.

Please let me know if you have any questions.

Thanks,
Xing

**Comment by MaxxLiu22** [comment]
I will go ahead to close this case, if you still have questions, feel free to reopen it or another case.
