### ISSUE TITLE
fortimanager_object_firewall_addrgrp - Dynamic Mapping - Member - Inappropriate value string

### ISSUE THREAD

**Issue by fortijames** [fortinetdev/terraform-provider-fortimanager#27]
In trying to dynamic map devices on an address group I am getting a type error. 
```
address_groups = {
  "terraform_group"={
    member=["terraform_lo0_fg1","terraform_lo1_fg1"],
    dynamic_mapping=[
      {device="FG2",vdom="root",member=["terraform_lo0_fg2"]}
    ]
  }
}
```

```
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/fmg_firewall_addrgrp/firewall_addrgrp.tf line 73, in resource "fortimanager_object_firewall_addrgrp" "address_group":
│   73:       member = dynamic_mapping.value.member
│ 
│ Inappropriate value for attribute "member": string required.
```

We can clearly see the API requires an array on the member field and not a string. 
```
#api_params: 192.168.0.3,apiadmin,/pm/config/adom/adom1/obj/firewall/addrgrp/host_group/dynamic_mapping/
[
   {
      "fabric-object" : 0,
      "color" : 0,
      "comment" : "i",
      "type" : 3,
      "_scope" : [
         {
            "name" : "FG1",
            "vdom" : "root"
         }
      ],
      "oid" : 4228,
      "allow-routing" : 0,
      "category" : 0,
      "uuid" : "8be7e190-a882-51ed-277f-b5287e17c8dc",
      "exclude" : 0,
      "member" : [
         "host2",
         "host1"
      ],
      "exclude-member" : []
   }
]
```

**Comment by lix-fortinet** [comment]
Hi @fortijames,

Thank you for raising this issue. The reason for this issue is the data type has been changed during different FortiManager versions in the REST API schema. We will fix this in the next release.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @fortijames,

This issue has been fixed in the latest release of FortiManager Terraform provider v1.8.0. Please switch to the latest version of FortiManager Terraform provider and try it out.

Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @fortijames,

We will close this issue since it has been fixed. Feel free to create a new issue is you have any questions.

Thanks,
Xing
