### ISSUE TITLE
Error importing a policy with internet_service_id

### ISSUE THREAD

**Issue by nikitakazantsev12** [fortinetdev/terraform-provider-fortimanager#28]
### Runtime environment
Provider version: 1.7.0
Terraform version: 1.3.9
Resource: fortimanager_packages_firewall_policy
Action: terraform import

### Issue
Trying to import a policy, which contains Google services under "dstaddr", I'm getting the following error:

```
│ Error: Error reading PackagesFirewallPolicy resource from API: Error reading internet_service_id: internet_service_id: '' expected type 'string', got unconvertible type '[]interface {}', value: '[65536 65537 65646]'
```

Those services are show in GUI as Google-Web, Google-Other and Google-Gmail.

### Proposed solution

Most likely, the provider code must be changed, so that in case of "internet_service_id" it accepts a list, not string.

**Comment by MaxxLiu22** [comment]
Hi @nikitakazantsev12 ,

Thank you for raising this issue, May I know which FMG version are you using? There may be some data type difference in varies FGM version, I test on FMG 7.2.1, everything is going well.

Thanks,
Maxx

**Comment by nikitakazantsev12** [comment]
We're on FortiManager-VM64-XEN v6.2.8 GA build1435 currently

**Comment by lix-fortinet** [comment]
Hi @nikitakazantsev12,

This issue has been fixed in the latest release of FortiManager Terraform provider v1.8.0. Please switch to the latest version of FortiManager Terraform provider and try it out.

Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @nikitakazantsev12,

We will close this issue since it has been fixed. Feel free to open a new issue if you have any questions.

Thanks,
Xing
