### ISSUE TITLE
provider resource arguments needing to be marked "sensitive"

### ISSUE THREAD

**Issue by redwoz** [fortinetdev/terraform-provider-fortimanager#34]
Terraform allows providers to control which resource arguments are considered sensitive to avoid them being leaked in plans and output variables. The following resource arguments for this provider are considered sensitive and are not marked as such, leaking into plans and output variables (note this is not an exhaustive list):

- **fortimanager_dvm_cmd_add_device** : device.admpass
- **fortimanager_object_system_sdnconnector** : client_secret

Can this be looked into.

**Comment by billy-lab3** [comment]
we have exact same issues and security concerns. 

Please find below for screenshots with the secret leaking in Terraform plan, 

**fortimanager_dvm_cmd_add_device**:

<img width="550" alt="image-2" src="https://user-images.githubusercontent.com/55371705/235070566-1a84d816-2ea9-4876-a004-e36aca3319fe.png">

**fortimanager_object_system_sdnconnector**:

<img width="548" alt="image-1" src="https://user-images.githubusercontent.com/55371705/235070467-c8abf37e-7f63-4a98-9f8f-495d419d3699.png">

**Comment by MaxxLiu22** [comment]
Hi @redwoz @billy-lab3 ，

Thank you for your suggestion, I talk to the development team with this improvement, they will add this feature at the next release.

Thanks,
Maxx

**Comment by warwick-lab3** [comment]
Hi @MaxxLiu22, are you able to please provide an ETA with regards to when the next release that includes this fix will land?

**Comment by MaxxLiu22** [comment]
Hi @warwick-lab3，

The next version will be released by the end of this month, it will fix most of the issue on terraform side.

Thanks,
Maxx

**Comment by lix-fortinet** [comment]
Hi @warwick-lab3, @redwoz, @billy-lab3,

This issue has been fixed in the latest release of FortiManager Terraform provider v1.8.0. Please switch to the latest version of FortiManager Terraform provider and try it out.

Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
We will close this issue since it has been fixed. Feel free to open a new issue if you have any questions.

Thanks,
Xing
