### ISSUE TITLE
fortimanager_system_route -  Error creating SystemRoute resource: err -60003: [entry not exist]

### ISSUE THREAD

**Issue by sognern** [fortinetdev/terraform-provider-fortimanager#37]
I'm trying to create a static route, running fortimanager; v7.2.2-build1334 230201 (GA);

resource "fortimanager_system_route" "test" {
  device = "vpn-tunnel"
  dst = [
        "10.0.0.0",
        "255.255.192.0",
  ]
  seq_num = 200
}

Error: Error creating SystemRoute resource: err -60003: [entry not exist]

**Comment by MaxxLiu22** [comment]
Hi @sognern ,

It looks like ``vpn-tunnel`` doesn't exist, I don't see there is a way to create a vpn tunnel on fmg, so you may need to choose a port as a device.

Thanks,
Maxx

**Comment by sognern** [comment]
It's an interface mapped to vpn phase 1.
Creating a test manually in fortimanager where I choose the mapped interface works. Terminal says this after creation;

config router static
    edit 2
        set dst 10.0.0.0 255.255.192.0
        set device "vpn-tunnel"
        set comment "azure services"
    next
end

**Comment by MaxxLiu22** [comment]
Hi @sognern ,

Thank you for your information, your CLI commands looks like run on the FGT, but resource "fortimanager_system_route" is used to configurate fortimanager's route setting, and unfortunately I don't find a resource to config FGT static router through FMG

![1](https://github.com/fortinetdev/terraform-provider-fortimanager/assets/98774290/23ef969a-9278-4c08-997a-993737feb92d)

, but we can set FGT static router through [script function](https://registry.terraform.io/providers/fortinetdev/fortimanager/latest/docs/resources/fortimanager_dvmdb_script) on FMG. Instruction is [here](https://docs2.fortinet.com/document/fortimanager/7.0.8/administration-guide/71780/cli-scripts), let me know if I misunderstand your question. 

Thanks,
Maxx

**Comment by MaxxLiu22** [comment]
Hi everyone,

I will proceed with closing this case. If you continue to experience any issues, please feel free to reopen it or open a new case.

Thank you,
Maxx
