### ISSUE TITLE
fortimanager_packages_firewall_policy: av_profile & ips_sensor keep missing after deployment

### ISSUE THREAD

**Issue by billy-lab3** [fortinetdev/terraform-provider-fortimanager#38]
**Description:** 

When creating firewall policy with 'fortimanager_packages_firewall_policy', we noticed that 'av_profile' & 'ips_sensor' properties keep missing from Terraform state file after deployment so that TF tries to update those settings every time when running the plan. 

TF plan:
<img width="544" alt="image" src="https://github.com/fortinetdev/terraform-provider-fortimanager/assets/55371705/95f3c076-7267-4990-bf05-fb8b9d48f6a2">

After 'terraform apply', those two settings seems never recorded to tfstate properly.
<img width="517" alt="image" src="https://github.com/fortinetdev/terraform-provider-fortimanager/assets/55371705/938be0ba-7653-447b-82ca-15411d14264e">

**Environment:**
  - Terraform v1.4.6
  - FortiManager provider v1.7.0

**Comment by MaxxLiu22** [comment]
@billy-lab3 ,

Thank you for raising this question, we need to set ``utm_status = "enable"`` first then set av_profile, after doing that you may find Terraform try to change some default value to null, we will fix that bug, by now you may need to manually set these arguments to their default value. sorry for the inconvenience.

Thanks,
Maxx

**Comment by billy-lab3** [comment]
thanks @MaxxLiu22 for your quick response and suggestion.

I can confirm the workaround works. Thanks.

**Comment by warwick-lab3** [comment]
Hi @MaxxLiu22, are you able to please provide an ETA with regards to when the next release that includes this fix will land?

**Comment by MaxxLiu22** [comment]
Hi @warwick-lab3 ,

Sorry for the late reply, I get a response from the dev team, they plan to have a release at the mid of July.

Thanks,
Maxx

**Comment by lix-fortinet** [comment]
Hi @billy-lab3, @warwick-lab3,

The issue of change default to null has been fixed in the latest release of FortiManager Terraform provider v1.8.0. Please switch to the latest version of FortiManager Terraform provider and try it out.

Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
We will close this issue since it has been fixed. Feel free to open a new issue if you have any questions.

Thanks,
Xing
