### ISSUE TITLE
Missing resource for central dnat & central dnat6

### ISSUE THREAD

**Issue by chjgdmn83** [fortinetdev/terraform-provider-fortimanager#41]
It seems that the implementation to deploy central dnat resources is still missing in the current release. Same for dnat6. 

--> /pm/config/central/dnat
--> /pm/config/central/dnat6

Would be great to see this fix soon in order to use the provider for policy packages that have central nat enable and need some vips to use. 

In case that I'm wrong please link me to the section in the provider docu I couldn't find.

Thanks in advance.

**Comment by MaxxLiu22** [comment]
Hi @chjgdmn83 

We have added [fortimanager_packages_central_dnat](https://registry.terraform.io/providers/fortinetdev/fortimanager/latest/docs/resources/fortimanager_packages_central_dnat), and [fortimanager_packages_central_dnat6](https://registry.terraform.io/providers/fortinetdev/fortimanager/latest/docs/resources/fortimanager_packages_central_dnat6) into our latest 1.10.0 FMG provider, you are free to upgrade to it and use them, I will go ahead to close this case, and you are welcome to reopen it or another case if you have any questions.

Thanks,
Maxx
