### ISSUE TITLE
SD-WAN template doesn't support metadata values.

### ISSUE THREAD

**Issue by parkerbrother1** [fortinetdev/terraform-provider-fortimanager#44]
I'm trying to import existing resources into Terraform.  Using wantemp_system_sdwan_members throws a type error on resources that have metadata variables assigned.  Importing a resource with a static cost works fine.

Error: Error reading WantempSystemSdwanMembers resource from API: Error reading cost: cost: '' expected type 'int', got unconvertible type 'string', value: '$(cost)'

**Comment by MaxxLiu22** [comment]
Hi @parkerbrother1 ,

Thank you for raising this issue, may I know which FOS version are you using and a screenshot of your sdwan members GUI setting? since on my side, ``cost`` only accepts an integer as value.

Thanks,
Maxx

**Comment by parkerbrother1** [comment]
Version 7.2.4.  See attached screenshot.
![Capture](https://github.com/fortinetdev/terraform-provider-fortimanager/assets/40617976/7154765e-a34a-431b-91f4-83c6bcbbc63f)

**Comment by MaxxLiu22** [comment]
Hi @parkerbrother1，

Thank you for your information and sorry for the inconvenience.  I can reproduce this and have acknowledged the dev team, they will fix this issue in the next release.

Thanks,
Maxx

**Comment by MaxxLiu22** [comment]
Hi @parkerbrother1 ,

FortiManager Provider 1.11.0 was released yesterday. Please upgrade to it, and this issue should be fixed.

Thanks,
Maxx

**Comment by MaxxLiu22** [comment]
Hi everyone,

I will proceed with closing this case. If you continue to experience any issues, please feel free to reopen it or open a new case.

Thank you,
Maxx
