### ISSUE TITLE
Multiple FSSO groups mapped to address object

### ISSUE THREAD

**Issue by davvelito85** [fortinetdev/terraform-provider-fortimanager#46]
Hi

When configuring an address group with type dynamic and subtype fsso i den GUI or CLI of FMG you are able to map multiple fsso groups to that address object. When doing it via the provider it expects a string and not a list of strings to be mapped to the address object, which makes it impossible to map multiple fsso groups to an address object.

The documentation (https://registry.terraform.io/providers/fortinetdev/fortimanager/latest/docs/resources/fortimanager_object_firewall_address) does however suggest that multiple groups are supported "FSSO group**(s)**".

**Comment by MaxxLiu22** [comment]
Hi @davvelito85 ,

Thank you for raising this issue and sorry for the late reply, I can reproduce it and have reported it to the development team for fixing, I will let you know once this issue has been fixed, sorry again for any inconvenience.

Thanks,
Maxx

**Comment by maetthew** [comment]
@MaxxLiu22 I work together with @davvelito85.

This surely will create problems when you have FSSO Group names that has commas in the name? We for instance have groups from AD synced with Forticollector that has commas in the name.

Imo this has to become a breaking change that employs a proper list with strings, or a second solution would be to have two separate, nearly identical, resources - one that accepts a string, and one that accepts a list.

**Comment by MaxxLiu22** [comment]
Hi @maetthew @davvelito85 ,

Thank you for raising this issue; indeed, it is a problem. I have reported it to the development team for improvement. Sorry for any inconvenience. You may use [fortios_json_generic_api](https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_json_generic_api) for a workaround solution for now.

Thanks,
Maxx

**Comment by MaxxLiu22** [comment]
Hi @maetthew @davvelito85 

Thank you for your patience. The FMG Terraform provider v1.12.0 has just been released, and this issue has been resolved. Please upgrade at your earliest convenience and try using single or double quotes with elements like ``fsso_group = "test1, 'test,2', \"test,3\""`` . Let us know if you encounter any further issues.

Thanks,
Maxx

**Comment by MaxxLiu22** [comment]
I will proceed with closing this case. However, please feel free to reopen it or open a new case if the issue persists or if you have any further questions.
