### ISSUE TITLE
Firewall object address dynamic mapping type incorrect

### ISSUE THREAD

**Issue by sidthetaff** [fortinetdev/terraform-provider-fortimanager#58]
Under
fortimanager_object_firewall_address
 dynamic_mapping {
    _scope {
      name = "XXXX"
      vdom = "root"
    }
    subnet = ["10.60.60.62","255.255.255.255"]
  }
  
  Subnet type is schema.TypeString
  "subnet": &schema.Schema{
	Type:     schema.TypeString,
	
	
This differs to the parent object, which has subnet schema.TypeList.

Doing an API pull from postman appears as if the parent object subnet type is list, but this is also true for the format for the dynamic mapping type. (code has been condensed for brevity)
                {
                    "dynamic_mapping": [
                        {
                            "_scope": [
                                {
                                    "name": "FGT_60F",
                                    "vdom": "root"
                                }
                            ],
                            "subnet": [
                                "10.60.0.1",
                                "255.255.255.255"
                            ],
                        },
                        {
                            "_scope": [
                                {
                                    "name": "FGT_91G",
                                    "vdom": "root"
                                }
                            ],
                            "subnet": [
                                "10.91.0.1",
                                "255.255.255.255"
                            ],
                        }
                    ],
                    "list": null,
                    "oid": 6265,
                    "tagging": null,
                    "name": "test dynamic",
                    "subnet": [
                        "127.0.0.1",
                        "255.255.255.255"
                    ],
                    "type": "ipmask",
                },

Terraform apply for parent object works fine, however adding in a dynamic mapping causes the following error:
╷
│ Error: Error creating ObjectFirewallAddress resource:
│ err -10: The data is invalid for selected url
│   with fortimanager_object_firewall_address.test1,
│   on main.tf line 20, in resource "fortimanager_object_firewall_address" "test1":
│   20: resource "fortimanager_object_firewall_address" "test1" {
│
╵
[main.txt](https://github.com/user-attachments/files/16334754/main.txt)

**Comment by MaxxLiu22** [comment]
Hi @sidthetaff ,

Thank you for bringing this issue to our attention. To ensure compatibility with all versions of FOS (some older versions support strings), we use a common method to split a string into a list at the backend. Could you please try setting the subnet like this?
``subnet = "10.60.60.66, 255.255.255.255"``, Please let me know if that doesn't work.

Thanks,
Maxx

**Comment by MaxxLiu22** [comment]
Hi @sidthetaff ,

I will proceed with closing this case. However, please feel free to reopen it or open a new case if the issue persists or if you have any further questions.

Thanks,
Maxx
