### ISSUE TITLE
metafields on fortimanager_dvm_cmd_add_device not working

### ISSUE THREAD

**Issue by isilweo** [fortinetdev/terraform-provider-fortimanager#8]
Hi,

I'm trying to add model device using fortimanager_dvm_cmd_add_device, however MetaFields are not working. Terraform is throwing an error when trying to use map/json because it needs string so currently there is no way of adding mapped values. I've tried using jsonencode( { name: value } ) format so it converts to string but when applying provider does not decode this so in Debug logs we see escaped string like 
`"meta fields": " { name: \"value\" } "`

in the outcome the model device is added but without having configured meta fields - they are empty

example code

```
resource "fortimanager_dvm_cmd_add_device" "trname" {
  fmgadom = "root"
  device {
    sn        = "FG40FITK2000000"
    deviceaction = "add_model"
    metafields = {
        "lan-ip" = "192.168.100.1"
    }
    mgmt_mode = "fmg"
    mr = "4"
    os_ver = "6.0"
    os_type = "fos"
    name = "test2134"
    platform_str = "FortiGate-40F-3G4G"
  }
 
}
```

**Comment by lix-fortinet** [comment]
Hi @isilweo,

Thank you for raising this issue. This issue is caused by the type change of argument `metafields` of REST API starting from FMG v6.4.7. Team is working on this issue. And we will fix it in the next release. Before that, you could use the generic resource as alternatives:
https://registry.terraform.io/providers/fortinetdev/fortimanager/latest/docs/resources/fortimanager_json_generic_api
For example:

```
resource "fortimanager_json_generic_api" "test1" {
  json_content = <<JSON
{
    "method": "exec",
    "params": [
        {
          "url": "/dvm/cmd/add/device",
          "data": {
            "adom": "root",
            "device": {
              "device action": "add_model",
              "meta fields": {
                "lan-ip": "192.168.100.1"
              },
              "mgmt_mode": "fmg",
              "mr": 4,
              "name": "test2134",
              "os_type": "fos",
              "os_ver": "6.0",
              "platform_str": "FortiGate-40F-3G4G",
              "sn": "FG40FITK2000000"
            }
          }
        }
    ]
}
JSON
}
```
Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @isilweo,

FortiManager Terraform provider v1.3.6 has fixed this issue. Please upgrade to v1.3.6 and have a try.

To avoid current user's failure, we keeps `metafields` as type of string, and adds a new argument `metafields_map` which is type of map for FortiManager version 6.4.7 and above.  For your case, please use `metafields_map` :
```
resource "fortimanager_dvm_cmd_add_device" "trname" {
  fmgadom = "root"
  device {
    sn        = "FG40FITK2000000"
    deviceaction = "add_model"
    metafields_map = {
        "lan-ip" = "192.168.100.1"
    }
    mgmt_mode = "fmg"
    mr = "4"
    os_ver = "6.0"
    os_type = "fos"
    name = "test2134"
    platform_str = "FortiGate-40F-3G4G"
  }
 
}
```

Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @isilweo,

I'm going to close this issue since it was resolved and has been inactive for a few months. You are very welcome to open a new issue if you have any other questions.
	
Thanks,
Xing
